VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
RGBLIGHT_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
MCU = STM32F103
MCU_SERIES = f1
MCU_LDSCRIPT = STM32F103xB_uf2boot

